### ISSUE TITLE
Console does not show at start

### ISSUE THREAD

**Issue by ygilquin-gpsw** [markknol/console-log-viewer#4]
Since last delivery of the script (sept 20th)  init state seems wrong.

When catching event on ~ char (maybe not the best char choice for Mac users btw), I see IS_CLOSED is false the first time but the console doesn't show.

**Comment by markknol** [comment]
Good point, I made a stupid mistake which should be fixed now.

What would be a better key for mac users?

**Comment by ygilquin-gpsw** [comment]
Wow... Quickest bug fix ever!
Anything that is reachable by a key present on the keyboard, tilde is alt+n and doesn't fire the right event. Maybe some keyCode from the numpad?

**Comment by markknol** [comment]
I don't have a mac so let me know what key would be nice. Tilde on windows felt good; I remember it was being used in quake and other old games :)

**Comment by ygilquin-gpsw** [comment]
Any key should be fine but I just found '@' has keycode 192. So I guess you could just document it and would have nothing to change in your code.

Another question, why don't you push the js file under github?

**Comment by markknol** [comment]
I put it in the gh-pages branch, because that is a way to serve/use the file directly using Github Pages.

**Comment by markknol** [comment]
There's nothing to do here, Ill just close it.
